### PR TITLE
Add description of CFEngine and links to learn more

### PR DESCRIPTION
**Pull request by atsaloli**

### CODE REVIEW

**Comment by miketheman** [comment]
Thanks!
Could you split up the paragraph onto separate lines, per our style guide?
https://github.com/opsschool/curriculum/blob/master/meta/style_guide.rst#spacing

**Comment by atsaloli** [comment]
@miketheman Done, thanks!

**Comment by miketheman** [comment]
Thanks!!

**Comment by atsaloli** [comment]
Thanks, Mike!

**Pull request merged**
