### PR TITLE
Dynamic routing

### PR DESCRIPTION
**Pull request by jeunito**
Added RIP and OSPF. Decided to remove IS-IS and EIGRP as I think RIP and OSPF would be enough as introductory routing protocols for both distance vector and link state routing. Not very familiar with BGP but I can work on it next.

### CODE REVIEW

**Comment by bmcmanus** [comment]
Jeunito, I know a lot about bgp and can provide some introductory examples. Interested in collaborating?

**Comment by mjulian** [comment]
@bmcmanus @jeunito What's your take on how something as specific and advanced as OSPF, EIGP, and BGP routing mesh with the goals and focus mentioned in the project's intro? (http://www.opsschool.org/en/latest/introduction.html#goals-and-focus)

Specifically, this bit:

> To have a complete syllabus for training smart persons with high potential who already have a basic
> understanding of Linux or other UNIX variant, to become strong junior systems administrators. This 
> course will focus on the Linux platform as a basis for competency in any UNIX ecosystem.

While I am **all for** more sysadmins knowing network engineering topics better, I'm curious what your thoughts are on how important it would be to junior sysadmins?

**Comment by jeunito** [comment]
@bmcmanus Nice. I don't know a lot about BGP myself so it will be good to be included in this branch.

**Comment by jeunito** [comment]
@mjulian I think I a short exposition will be enough without going into much detail. In other words, the key is for people new to the field to at least know they are there.

**Comment by mjulian** [comment]
@jeunito That makes sense to me. Basically something like "Here's what BGP is and why it matters"?

**Pull request merged**
